services:

  comfyui:
    init: true
    container_name: comfyui_cu124_megapak
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot:cu124-megapak"
    ports:
      - "8124:8188"
    volumes:
      - "./storage:/root"
    environment:
      - CLI_ARGS=
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
